### ISSUE TITLE
README needs more information on how to run the project

### ISSUE THREAD

**Issue by rsmets** [ai16z/LiveVideoChat#1]
I am trying to get this project running locally but would appreciate some direction.

I have supplied it with OpenAI, ElevenLabs, and Simli API Keys but am having trouble understanding what app is supposed to be pointed at via the `VITE_COMPLETION_ENDPOINT` env var. I'm guessing that is the Eliza framework itself? 

Explicit information about this would be very helpful.

**Comment by lalalune** [comment]
thanks for your contribution, closing this as i've merged your PR
